#!/bin/sh
/home/swetank/.local/bin/wal -t -s -i /home/swetank/Pictures/kabegami/wal
sudo bash /home/swetank/.local/bin/rgbkeys

# Doesn't change with dark theme on gnome so do add this in 
# .local/lib/python.../pywal/wallpapers.py

# elif "gnome" in desktop or "unity" in desktop:
#        util.disown(["gsettings", "set",
#                     "org.gnome.desktop.background",
#                     "picture-uri-dark", "file://" + urllib.parse.quote(img)])
