[[manager.prepend_keymap]]
on   = "P"
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"

# keymap.toml
[[manager.prepend_keymap]]
on   = "M"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"
