[line_break]
disabled = true

[package]
disabled = true

[python]
disabled = true

[java]
disabled = true

[nodejs]
disabled = true

[username]
format = '\[[$user]($style_user)@'
style_user = 'white bold'
style_root = 'white bold'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$hostname]($style)\] '
#trim_at = "-"
style = "white bold"
disabled = false

[sudo]
format = '\[[as $symbol]($style)\]'
