[line_break]
disabled = true

[package]
disabled = true

[python]
disabled = true

[java]
disabled = true

[nodejs]
disabled = true

[username]
#style_user = "bold dimmed blue"
format = "[$user](cyan bold)@"
#show_always = true

[hostname]
#ssh_only = false
format = "[$hostname]($style) "
#trim_at = "-"
#style = "bold dimmed white"
#disabled = false


