#---------Alacritty uses TOML now :) Feb-4-2024-------------

import=["~/.cache/wal/alacritty.toml"]

#[[colors.indexed_colors]]
#color = "#FAB387"
#index = 16
#
#[[colors.indexed_colors]]
#color = "#F5E0DC"
#index = 17
#
#[colors.bright]
#black = "#585B70"
#blue = "#89B4FA"
#cyan = "#94E2D5"
#green = "#A6E3A1"
#magenta = "#F5C2E7"
#red = "#F38BA8"
#white = "#A6ADC8"
#yellow = "#F9E2AF"
#
#[colors.cursor]
#cursor = "#F5E0DC"
#text = "#1E1E2E"
#
#[colors.dim]
#black = "#45475A"
#blue = "#89B4FA"
#cyan = "#94E2D5"
#green = "#A6E3A1"
#magenta = "#F5C2E7"
#red = "#F38BA8"
#white = "#BAC2DE"
#yellow = "#F9E2AF"
#
#[colors.hints.end]
#background = "#A6ADC8"
#foreground = "#1E1E2E"
#
#[colors.hints.start]
#background = "#F9E2AF"
#foreground = "#1E1E2E"
#
#[colors.normal]
#black = "#45475A"
#blue = "#89B4FA"
#cyan = "#94E2D5"
#green = "#A6E3A1"
#magenta = "#F5C2E7"
#red = "#F38BA8"
#white = "#BAC2DE"
#yellow = "#F9E2AF"
#
#[colors.primary]
#background = "#000000"
#bright_foreground = "#CDD6F4"
#dim_foreground = "#CDD6F4"
#foreground = "#f0f0f0"
#
#[colors.search.focused_match]
#background = "#A6E3A1"
#foreground = "#1E1E2E"
#
##[colors.search.footer_bar]
##background = "#A6ADC8"
##foreground = "#1E1E2E"
#
#[colors.search.matches]
#background = "#A6ADC8"
#foreground = "#1E1E2E"
#
#[colors.selection]
#background = "#F5E0DC"
#text = "#1E1E2E"
#
#[colors.vi_mode_cursor]
#cursor = "#B4BEFE"
#text = "#1E1E2E"

[font]
size = 12.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Medium"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[96;5u"
key = "`"
mods = "Control"

[window]
decorations = "Full"
dynamic_padding = true
opacity = 0.92

[window.dimensions]
columns = 118
lines = 38

[window.padding]
x = 10
y = 10
