require('etank.settings')
require('etank.plugins')
require('etank.highlights')
require('etank.map')
require('etank.lualine')
require('etank.toggleterm')
require('etank.lspconfig')
require('etank.bufferline')
require('etank.treesitter')
require('etank.nvimtree')
require("etank.telescope")
require('etank.indent')
require('etank.comment')
--require('etank.rosepine')
--require('etank.catppuccin')
--require('etank.nord')
--Pywal AlphaTechnology
--local pywal = require('pywal')
--pywal.setup()
